### ISSUE TITLE
Broken license link

### ISSUE THREAD

**Issue by scottveirs** [SalishSeaCast/salishsea-site#64]
Using OSX+Chrome today, I selected the License link from the About dropdown menu -- 

<img width="721" alt="Screenshot 2024-01-26 at 2 03 25 PM" src="https://github.com/SalishSeaCast/salishsea-site/assets/14044595/e0783f41-9d8d-4771-b17d-99ee8e31f64e">

I received a 500 error --

<img width="533" alt="Screenshot 2024-01-26 at 2 02 23 PM" src="https://github.com/SalishSeaCast/salishsea-site/assets/14044595/e3643285-0001-4524-9489-06f0ab5795c4">

**Comment by douglatornell** [comment]
Thanks for the report @scottveirs! Fixed now.  I'm embarrassed by how long this issue existed before you drew attention to it.
